[workspace]
members = [
  "crates/api",
  "crates/macros",
  "crates/cli",

  # examples
  "examples/demo",
]

[patch.crates-io]
node-api-macros = { path = "./crates/macros" }
node-api-rs = { path = "./crates/api" }
