[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.nodex-api]
path = "../../crates/nodex-api"
features = ["v8"]

[dependencies.nodex]
path = "../../crates/nodex"
features = ["v8"]
