# CI flow
on: [push, pull_request]
name: CI

jobs:
  check:
    name: Check & format & lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test - v1
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p nodex-api --no-default-features --features=v1

      - name: Run cargo test - v2
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p nodex-api --no-default-features --features=v2

      - name: Run cargo test - v3
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p nodex-api --no-default-features --features=v3

      - name: Run cargo test - v4
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p nodex-api --no-default-features --features=v4

      - name: Run cargo test - v5
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p nodex-api --no-default-features --features=v5

      - name: Run cargo test - v6
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p nodex-api --no-default-features --features=v6

      - name: Run cargo test - v7
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p nodex-api --no-default-features --features=v7

      - name: Run cargo test - v8
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p nodex-api --no-default-features --features=v8

  examples:
    name: Run Demo Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - run: cargo build -p demo -p func -p promise -p tsfn -p element
      - run: cp target/debug/libdemo.so demo.node

      - name: Install nodejs - v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: bash examples/demo.sh
      - run: bash examples/func.sh
      - run: bash examples/promise.sh
      - run: bash examples/tsfn.sh
      - run: bash examples/element.sh

      - name: Install nodejs - v17
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - run: bash examples/demo.sh
      - run: bash examples/func.sh
      - run: bash examples/promise.sh
      - run: bash examples/tsfn.sh
      - run: bash examples/element.sh

